import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>BlackHeart&apos;s Portfolio || Home</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        <h1>BlackHeart&apos;s Portfolio</h1>
      </main>
    </>
  );
}
